spring:
  application:
    name: ai-code-mother-me
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_code_mother_me
    username: root
    password: 1234

server:
  port: 8123
  servlet:
    context-path: /api
#springdoc-openapi ???? Swagger ??
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wyb.aicodemotherme.controller
#knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # ??????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????
      logic-delete-value: 1 # ?????????? 1?
      logic-not-delete-value: 0 # ?????????? 0?

