spring:
  application:
    name: ai-code-mother-me
server:
  port: 8123
  servlet:
    context-path: /api
#springdoc-openapi ???? Swagger ??
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.wyb.aicodemotherme.controller
#knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn